### ISSUE TITLE
Crashing on Windows 7x64?

### ISSUE THREAD

**Issue by cemerson** [gotdibbs/GistInTime#7]
I love the idea/sound of this app ... but it seems to be crashing for me every time I try it on my Windows 7 x64 machine. Can you advise? Video of my issue here: http://goo.gl/FQKIVd

Thanks in advance if you can help!

**Comment by gotdibbs** [comment]
Missed the email notification of this issue, sorry for the delay. I'll try to take a look today. I see a NullReferenceException occurring in your video so that should give me something to look into.

**Comment by gotdibbs** [comment]
Looks like the API changed. I've updated the app to reflect those changes and published a new version. Sadly my signing cert expired, so the built-in auto update will not work for this update.
